### ISSUE TITLE
Betza Notation Working Inconsistently

### ISSUE THREAD

**Issue by PraseodymiumSpike** [ianfab/fairyground#12]
[cannonshogi:shogi]
shogiPawn = -
soldier = p
dropNoDoubled = -
cannon = u
janggiCannon = a
customPiece1 = c:mBcpB
customPiece2 = i:pB
customPiece3 = w:RpRFpA
customPiece4 = f:BpBWpD
promotedPieceType = u:w a:w c:f i:f
startFen = lnsgkgsnl/1rci1uab1/p1p1p1p1p/9/9/9/P1P1P1P1P/1BAU1ICR1/LNSGKGSNL

Why can't I do 1.Ic5 with this definition?

**Comment by ianfab** [comment]
It's surprising behavior, but in a weird way correct. `immobilityIllegal` disables all moves that lead to a piece having no moves, which in this case applies.

**Comment by PraseodymiumSpike** [comment]
But it can capture on g9 and move to f8. In fact, the page I got this example game from even points that out!

**Comment by PraseodymiumSpike** [comment]
Sorry, it can capture on f8 and can't go to g9. I apologize for the confusion. The piece on f8 was invisible.
