### ISSUE TITLE
Add complete piece set

### ISSUE THREAD

**Issue by ianfab** [ianfab/fairyground#2]
Add SVGs for all piece letters from a-z and from +a to +z for the standard themes (e.g., merida, cburnett) to have visible pieces for all variants.

**Comment by PraseodymiumSpike** [comment]
I think that it should also be that each piece letter is actually different.

**Comment by PraseodymiumSpike** [comment]
For example, H and J are the same right now.

**Comment by PraseodymiumSpike** [comment]
# List of Potential Merida Pieces to Add from Other Projects
black "D" piece: https://github.com/abgros/chessboi/blob/master/graphics/shinobimirror/bD.png (somewhat off style)
white "Y" piece: https://github.com/gbtami/pychess-variants/blob/master/static/images/pieces/orda/merida/wY.svg

might add more as time goes on

**Comment by dpldgr** [comment]
I've been working on some graphics that seem to complete this enhancement, is this the kind of thing that you're looking for @ianfab? A grey piece background indicates an unpromoted piece, a gold piece background indicates a promoted piece.
![Screenshot 2023-10-12 135923](https://github.com/ianfab/fairyground/assets/144766863/f8b1ae61-7741-41e5-b547-df004165f618)
![Screenshot 2023-10-12 140037](https://github.com/ianfab/fairyground/assets/144766863/f8099beb-23ca-40a8-9acc-d1f51abdd25a)

**Comment by yjf2002ghty** [comment]
> I've been working on some graphics that seem to complete this enhancement, is this the kind of thing that you're looking for @ianfab? A grey piece background indicates an unpromoted piece, a gold piece background indicates a promoted piece. ![Screenshot 2023-10-12 135923](https://user-images.githubusercontent.com/144766863/274497055-f8b1ae61-7741-41e5-b547-df004165f618.png) ![Screenshot 2023-10-12 140037](https://user-images.githubusercontent.com/144766863/274497111-f8099beb-23ca-40a8-9acc-d1f51abdd25a.png)

This looks much better than the letters theme currently. But what the title means is that we need to find full merida / cburnett SVGs that covers a-z and +a-+z.
In most cases, using different graphs for the pieces can help users recognize the pieces faster than using letters.

**Comment by dpldgr** [comment]
> This looks much better than the letters theme currently. But what the title means is that we need to find full merida / cburnett SVGs that covers a-z and +a-+z. In most cases, using different graphs for the pieces can help users recognize the pieces faster than using letters.

Hmmm. The same letter might signify two different pieces in different variants (eg. an A moves as a BN in "capablanca", but a QN in "amazon"), and two different letters might also signify the same piece movement in different variants. In the A example it might be more misleading than helpful to use the same A graphic in both "capablanca" and "amazon". There's also surely more than 26 different pieces just in the variants that fairyground supports by default. It does seem like an impossible task, or am I missing something?

**Comment by yjf2002ghty** [comment]
> > This looks much better than the letters theme currently. But what the title means is that we need to find full merida / cburnett SVGs that covers a-z and +a-+z. In most cases, using different graphs for the pieces can help users recognize the pieces faster than using letters.
> 
> Hmmm. The same letter might signify two different pieces in different variants (eg. an A moves as a BN in "capablanca", but a QN in "amazon"), and two different letters might also signify the same piece movement in different variants. In the A example it might be more misleading than helpful to use the same A graphic in both "capablanca" and "amazon". There's also surely more than 26 different pieces just in the variants that fairyground supports by default. It does seem like an impossible task, or am I missing something?

Full merida / cburnett SVGs are used by the default theme that applicates to the variants which currently does not have a specialized theme. This is used as a fallback to ensure that all pieces can be rendered (e.g. The stardust variant has most of its pieces not rendered).
In terms of "capablanca" and "amazon", they don't have their own themes and uses the default theme as fallback which can cause ambiguous piece moves. The best way is to design specialized themes for all variants, but it is a large work.
Letter themes are used for recognizing the piece ids of each piece that are used in fairy stockfish and FEN. They are used for development purposes instead of playing.

**Comment by dpldgr** [comment]
> > > This looks much better than the letters theme currently. But what the title means is that we need to find full merida / cburnett SVGs that covers a-z and +a-+z. In most cases, using different graphs for the pieces can help users recognize the pieces faster than using letters.
> > 
> > 
> > Hmmm. The same letter might signify two different pieces in different variants (eg. an A moves as a BN in "capablanca", but a QN in "amazon"), and two different letters might also signify the same piece movement in different variants. In the A example it might be more misleading than helpful to use the same A graphic in both "capablanca" and "amazon". There's also surely more than 26 different pieces just in the variants that fairyground supports by default. It does seem like an impossible task, or am I missing something?
> 
> Full merida / cburnett SVGs are used by the default theme that applicates to the variants which currently does not have a specialized theme. This is used as a fallback to ensure that all pieces can be rendered (e.g. The stardust variant has most of its pieces not rendered). In terms of "capablanca" and "amazon", they don't have their own themes and uses the default theme as fallback which can cause ambiguous piece moves. The best way is to design specialized themes for all variants, but it is a large work. Letter themes are used for recognizing the piece ids of each piece that are used in fairy stockfish and FEN. They are used for development (e.g. Designing a variant) purposes instead of playing.

In the absence of being able to map specific letters to specific graphics, the approach I've used seems to be the only way of guaranteeing that pieces will actually be rendered for an arbitrary variant. End users can also use the "Show legal moves" option to figure out how pieces are moved. For my variants, I actually developed icons that explicitly show how they can move to help users learn how to play much quicker than they otherwise could. I wonder if there's some way of doing that on the fly for arbitrary pieces.

**Comment by ianfab** [comment]
Exactly, this would just be a first simple step to improve usability. When no SVG is available, the piece is invisible. When having a fixed SVG per letter it might be the "wrong" one from the user perspective. Having it customized per variant and/or user selectable would be the best, but is highest effort. So #5 would likely make this issue obsolete, but this one is way less effort, so I still think it will be the intermediate solution.

**Comment by ianfab** [comment]
Closed in #54
