### ISSUE TITLE
cant chain camel or zebra moves

### ISSUE THREAD

**Issue by Moonyol** [ianfab/fairyground#24]
[chain:chess]
customPiece1 = M:C0
startFen = rnbqkbnr/pppppppp/8/8/8/8/8/4M3 w kq - 0 1

if u replace it with a knight move, customPiece1 = M:N0, then it would work properly and look like this
![image](https://user-images.githubusercontent.com/92951072/236633453-7ea1d1a9-4e7a-4319-9093-687d5cab18df.png)
but if u use a camel or zebra then it has no moves

**Comment by ianfab** [comment]
This limitation is inherited from Fairy-Stockfish and is tracked as issue https://github.com/fairy-stockfish/Fairy-Stockfish/issues/499, so I am closing this one.
