### ISSUE TITLE
Use pieceToCharTable

### ISSUE THREAD

**Issue by PraseodymiumSpike** [ianfab/fairyground#28]
I think FairyGround should use the `pieceToCharTable` option with Merida-like versions of the XBoard piece images. This would allow us to use whichever letters we want and still have the pieces be visible.

**Comment by yjf2002ghty** [comment]
Currently [ffish.js](https://www.npmjs.com/package/ffish-es6) library does not export all game options to fairyground. `pieceToCharTable` is also not exported. Therefore this function is not available until ffish.js supports exporting all game rule information. There is a similar issue #27 .

**Comment by ianfab** [comment]
Given the available complete piece sets and custom graphics I consider this solved.
