### ISSUE TITLE
Add "Settings: [nodes]" option to Advanced Analysis page.

### ISSUE THREAD

**Issue by dpldgr** [ianfab/fairyground#33]
It'd be nice to be able to specify a number of nodes per move (mapping to uci "go nodes" under the hood) in the advanced options for fairyground. That would enable games of a more consistent quality to be played/generated as the engine's search isn't effected by how loaded or fast a processor is.

**Comment by ianfab** [comment]
If you just want reproducibility you can also simply use depth limited search. Support node limit could be added for completeness, but doesn't seem very critical to me given that depth limited search is already supported.

**Comment by dpldgr** [comment]
You're right that you can limit depth to make things more reproducible, but it can have an impact on the quality of a search (particularly in the endgame) as depths can get quite high when fewer pieces are on the board. Limiting depth can lead to an important move being missed which costs you the game. If using a node limit this doesn't happen, you still get the benefits of deeper search without being impacted by other things the system might be doing at any given moment.

I'm happy to take the lead on this one, I got fairyground up and running on my machine yesterday so I can now do some development work.
