### ISSUE TITLE
Add move disambiguation

### ISSUE THREAD

**Issue by ianfab** [ianfab/fairyground#4]
In case of ambiguous user input (e.g., a7a8q/r/b/n) add dropdown/selection for disambiguation. How does this work in chessgroundx?

**Comment by gbtami** [comment]
Chessground(x) knows nothing about promotion/gating concepts. They are implemented in pychess/lichess.
https://github.com/gbtami/pychess-variants/blob/master/client/promotion.ts
https://github.com/gbtami/pychess-variants/blob/master/client/gating.ts

**Comment by ianfab** [comment]
Closed with #26.
