### ISSUE TITLE
Is it possible to see the evaluation of a position in analysis mode?

### ISSUE THREAD

**Issue by mrgwbland** [ianfab/fairyground#52]
![image](https://github.com/ianfab/fairyground/assets/30123279/fd651b01-af34-4d27-b707-54ec399047be)
As you can see from the image I am analysing my own custom variant and I can see the best move but no +/- evaluation to say who's winning. 

Also is it possible to show the best move arrow on the board so I don't have to look at the console because I'm quite slow with move notation.

**Comment by ianfab** [comment]
cp 0 means it evaluates the position as equal. If you play on it likely should change.

Parsing the raw engine output and displaying it in a more accessible way, including arrows, definitely should be done at some point, but hasn't been yet.

**Comment by mrgwbland** [comment]
@ianfab Thank you very much for your reply, also I have another issue please can you help me.
I want a piece that moves like a pawn but can move on diagonals and capture forwards, this works however double move on the first move doesn't, is there something wrong with my implementation?
customPiece1 = S:fWfFifmnDifmnA

**Comment by ianfab** [comment]
I would guess something could be off with the "doubleStepRegion", but hard to say without more context. Usually it is best to ask such questions on the Fairy-SF discord and post your whole variant config there for context. Github issues should normally mostly be reserved for bug reports and feature requests.

**Comment by mrgwbland** [comment]
Sorry, will do, didn't know how to ask.
