### ISSUE TITLE
Does clearing hash after every move reduce engine strength?

### ISSUE THREAD

**Issue by yjf2002ghty** [ianfab/fairyground#71]
I am reviewing the code written before and noticed that currently the UI sends a clear hash command to in browser fairy-stockfish after every move. Does this reduce engine strength? If yes, I'll create a pull request to fix this.

This does not affect binary engines.

**Comment by ianfab** [comment]
Yes, it does. Clearing hash should happen when hash entries become irrelevant, e.g., when changing the variant or setting up a completely new position, but after merely making a move hash will still be highly relevant and beneficial.

**Comment by yjf2002ghty** [comment]
OK, I'll fix this.
