### ISSUE TITLE
Amazon Chess

### ISSUE THREAD

**Issue by DSARichard** [ianfab/fairyground#9]
Amazon chess replaces queens with amazons, which are queen-knight hybrids. In Fairyground, there is a preset of amazon chess. However, the amazons are displayed as archbishops, which may be due to the fact that the names of both start with "a". As archbishops are quite common in fairy chess variants, displaying archbishop-seeming amazons may be quite misleading. I have not checked other variants' archbishops, but most of those are very likely correct. Could these amazons be displayed in another way? (pieceToCharTable)

**Comment by ianfab** [comment]
Yes, the images currently are purely based on the letter, just to have something displayed for each variant. A more flexible generic solution would be nice. As that idea is already filed as #5, I am closing this one here.
